### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by waiholiu** [dferber90/meteor-prerender#16]
When I execute

curl http://localhost:3000/?_escaped_fragment_=

I just get an empty body and it never hits the prerender.io service

**Comment by dferber90** [comment]
A new version of `prerender-node` was released, so I made a new release of this package. I didn't test it as I'm not using this package any longer.

You can install the previous version of this package and see whether it works with that. If it works with the previous version and doesn't work with the current version, then it's a regression.

Let me know in case you find out why it isn't working.

**Comment by wiiiimm** [comment]
@waiholiu the suffix is 

`?_escaped_fragment_=` 

**NOT** 

`?escaped_fragment=`

**Comment by waiholiu** [comment]
Hi, the problem ended up being on my side. Firstly, I stupidly forgot that my settings.json file needs to be explicitly included in the local environment (I had been using it in my MUP deploy) so that was dumb. And then I didn't realize that you had to put a token into the settings.json even if it was a local server. So once I put a dummy token file in, it fixed everything and I can actually just use the original package.

Just wondering though, now that I have the original package working, what is this package doing that is different? Is it just to avoid the "res.send(status, body): Use res.status(status).send(body) instead" message?

**Comment by dferber90** [comment]
As noted in the [in the README](https://github.com/dferber90/meteor-prerender#prior-art):

> The initial version by @dfischer uses the outdated prerender-node module. This package uses the latest version, allowing it to work without all the boilerplate

I guess by the "initial version" you are talking about the one of dfischer. That package doesn't use an up-to-date version of the npm module `prerender-node`. `prerender-node` has been rewritten to work without express, making integration into Meteor straightforward. dfischer hasn't updated his package since then, so that version is still using monkey patching to integrate `prerender-node`.

The work in `prerender-node` for the easier integration was done by [Arunoda](https://github.com/arunoda/). Unfortunately dfischer hasn't updated his package to make use of the easier integration. So I created my own. You can compare the sources to see the difference.

**Comment by wiiiimm** [comment]
you should release this under a better name to avoid confusion. like meteor-prerender-native or something.

**Comment by dferber90** [comment]
How would that be better?

**Comment by waiholiu** [comment]
Hi dferber, 
I had a look and yours does seem cleaner, so I am going to use yours over the original. Not to mention the fact the original solution does'nt seem to support sites that only have http.

Quick question, why do you do a "if (token)" check?

A token is only mandatory if you're using the prerender.io service - because I'm using my own installation of prerender, I need to put a dummy value in the token.

**Comment by dferber90** [comment]
As stated in the README, this package is more of a reference on how to integrate prerender than an actual package. If you need modifications, go with your own package based on this one.

I'm using the check so prerender can be disabled during development by putting a falsy value as the token.
